### ISSUE TITLE
Using this component with bottom tabbar component

### ISSUE THREAD

**Issue by dpatel** [marcelxsilva/tabbar-animation-challenge#1]
I am wondering if it is possible to use this with the bottom tab bar component?

**Comment by marcelxsilva** [comment]
Yes, it is possible :)

**Comment by dpatel** [comment]
Can you please guide me? I tried to set as TabBarComponent but it didn't work.

**Comment by marcelxsilva** [comment]
yes i can, you import the TabBar component to the tabBarComponent, the TabBar component will receive the navigation object for the purposes and from there you can use it as an event for each button.

**Comment by dpatel** [comment]
I give a try and followed the way similar to https://github.com/enaydyonov/react-native-bubble-tab-bar/blob/master/src/navigation/index.js but no luck. Do you have any tutorial which can guide?

**Comment by marcelxsilva** [comment]
yes, you can see this example project: https://github.com/marcelxsilva/nejoy-app

**Comment by marcelxsilva** [comment]
yes, you can look at this example project :https://github.com/marcelxsilva/nejoy-app

**Comment by dpatel** [comment]
Sorry but page not found for that link. https://github.com/marcelxsilva/nejoy-app

**Comment by marcelxsilva** [comment]
now it's ok

**Comment by dpatel** [comment]
Cool thank I will look into it. Appreciate your help.

**Comment by dpatel** [comment]
Thanks for that tutorial. Have implemented it successfully. However, I am not able to change the fill color of the path. 

`
<View {...{ width, height }}>
          <AnimatedSvg
            width={width * 2}
            style={{backgroundColor:'#AAE8FF', transform: [{ translateX }] }}
            {...{ height, }} >
            <Path {...{ d }} fill='red' />
          </AnimatedSvg>
          <View style={[StyleSheet.absoluteFill]}>
          <StaticTabbar
              value={translateX}
              tabs={routes}             
              {...this.props}
            />
          </View>
        </View>
        <SafeAreaView style={styles.safeArea} />
`

As you can see I am trying to apply a red color but it is not working. 

![image](https://user-images.githubusercontent.com/2101313/82857586-0f77a500-9f2f-11ea-8345-7e9116fd7dfa.png)

**Comment by dpatel** [comment]
That works perfectly. Thanks for the help. I am trying to render the text using 
`<Animated.View style={[styles.tab, { opacity }]}>
                    {renderIcon({ route, focused: isRouteActive, tintColor })}
                  </Animated.View>
                  <Animated.Text style={{color:'blue' }}>{route.title}</Animated.Text>`

and also tried using renderLabel 
`  <Animated.View> 
                  <View style={styles.circle}> 
                    {renderIcon({ route, focused: isRouteActive, tintColor })}  
                  </View>  
                </Animated.View>  
                {renderLabel({route, focused:isRouteActive, tintColor})}` 

But it is not showing the label. Do you have any idea to add label?
